# Curated Local Medicine Database for PharmaGlobe

MEDICINE_DATABASE = [ { 'benefits': [ 'Highly effective pain relief',
                  'Fast-acting formula',
                  'Gentle on the stomach compared to some older NSAIDs'],
    'category': 'Pain Reliever',
    'country': 'Japan',
    'dosage': 'Adults (15+): Take 1 tablet up to 2 times a day. If symptoms persist, a 3rd dose may be taken. Avoid '
              'taking on an empty stomach. Space doses at least 4 hours apart.',
    'generic_name': 'Loxoprofen Sodium Hydrate',
    'image_url': 'images/med_0.png',
    'name': 'Loxonin S (ロキソニンS)',
    'price': '¥650 - ¥800 (12 tablets)',
    'shop_link': 'https://www.amazon.co.jp/s?k=ロキソニンS',
    'uses': ['Headaches', 'Menstrual cramps', 'Toothaches', 'Fever reduction', 'Joint pain'],
    'warnings': [ 'Do not take if under 15 years old.',
                  'Do not take if you have stomach ulcers, severe kidney, liver, or heart issues.',
                  'Avoid if you have asthma triggered by aspirin or other NSAIDs.',
                  'Consult a doctor if pregnant or breastfeeding.']},
  { 'benefits': [ 'Dual-action formula with Dibuffer HT to protect the stomach lining',
                  'Fast absorption',
                  'Contains no sleep-inducing ingredients'],
    'category': 'Pain Reliever',
    'country': 'Japan',
    'dosage': 'Adults (15+): 2 tablets per dose, up to 2 times a day. Space doses at least 6 hours apart. Take with '
              'water, preferably not on an empty stomach.',
    'generic_name': 'Aspirin (Acetylsalicylic Acid)',
    'image_url': 'images/med_1.png',
    'name': 'Bufferin A (バファリンA)',
    'price': '¥800 - ¥1,200 (40 tablets)',
    'shop_link': 'https://www.amazon.co.jp/s?k=バファリンA',
    'uses': ['Headaches', 'Fever reduction', 'Muscle pain', 'Toothache', 'Shoulder stiffness pain'],
    'warnings': [ "Do not give to children under 15 years old (risk of Reye's syndrome).",
                  'Do not take if you are within 12 weeks of delivery (pregnancy).',
                  'Avoid alcohol while taking this medication.',
                  'Consult a doctor if taking blood thinners.']},
  { 'benefits': [ 'Specially formulated for fast headache relief',
                  'Contains magnesium oxide to speed up absorption and protect stomach'],
    'category': 'Pain Reliever',
    'country': 'Japan',
    'dosage': 'Adults (15+): 2 tablets per dose, up to 3 times a day. Space doses at least 4 hours apart. Avoid taking '
              'on an empty stomach.',
    'generic_name': 'Ibuprofen + Allylisopropylacetylurea + Anhydrous Caffeine',
    'image_url': 'images/med_2.png',
    'name': 'EVE Quick (イブクイック)',
    'price': '¥900 - ¥1,400 (40 tablets)',
    'shop_link': 'https://www.amazon.co.jp/s?k=イブクイック',
    'uses': ['Severe headaches', 'Fever reduction', 'Menstrual pain', 'Sore throat pain'],
    'warnings': [ 'Do not take if under 15 years old.',
                  'May cause drowsiness; do not drive or operate machinery after taking.',
                  'Avoid taking other cold medicines or sedatives concurrently.',
                  'Limit use if you have history of asthma.']},
  { 'benefits': [ 'All-in-one multi-symptom cold relief',
                  'Clears phlegm and suppresses coughing',
                  'Very popular standard household cold medicine'],
    'category': 'Cold & Flu',
    'country': 'Japan',
    'dosage': 'Adults (15+): 1 packet or 3 tablets, 3 times daily. Children (12-14): 2/3 packet or 2 tablets, 3 times daily. Under 12: Do not use.',
    'generic_name': 'Guaifenesin + Dihydrocodeine Phosphate + Acetaminophen + Chlorpheniramine Maleate',
    'image_url': 'images/med_3.png',
    'name': 'Pabron Gold A (パブロンゴールドA)',
    'price': '¥1,300 - ¥1,800 (44 packets / 210 tablets)',
    'shop_link': 'https://www.amazon.co.jp/s?k=パブロンゴールドA',
    'uses': ['Cough', 'Sputum/Phlegm', 'Sore throat', 'Runny nose', 'Fever', 'Chills', 'Muscle ache'],
    'warnings': [ 'Do not give to children under 12 years old.',
                  'Causes drowsiness. Do not drive or operate machinery.',
                  'Contains codeine; use with caution. Do not use long-term.',
                  'Avoid alcohol and other sedatives.']},
  { 'benefits': [ 'Traditional Japanese medicine trusted for over 140 years',
                  'Natural aromatic herbs refresh the stomach',
                  'Fast relief from acid reflux and bloating'],
    'category': 'Digestive Health',
    'country': 'Japan',
    'dosage': 'Adults (15+): 1 spoonful of powder or 1 sachet, 3 times daily. Children (8-14): 1/2 spoonful or 1/2 sachet, 3 times daily. Under 8: Do not use.',
    'generic_name': 'Herbal stomachic blend (Cinnamon, Fennel, Nutmeg) + Antacids (Sodium Bicarbonate, Calcium '
                    'Carbonate)',
    'image_url': 'images/med_4.png',
    'name': "Ohta's Isan (太田胃散)",
    'price': '¥900 - ¥1,300 (140g powder)',
    'shop_link': 'https://www.amazon.co.jp/s?k=太田胃散',
    'uses': ['Heartburn', 'Stomach upset', 'Overeating/drinking', 'Indigestion', 'Loss of appetite'],
    'warnings': [ 'Do not give to infants under 8 years old.',
                  'Contains sodium; consult doctor if on a low-salt diet.',
                  'Do not use if you have severe kidney disease.',
                  'Avoid long-term continuous use (limit to 2 weeks unless directed).']},
  { 'benefits': [ 'Non-drowsy antihistamine',
                  'Does not impair performance or concentration',
                  'Works 24 hours with twice-daily dosing'],
    'category': 'Allergy',
    'country': 'Japan',
    'dosage': 'Adults (15+): 1 tablet, twice a day (morning and evening) with water.',
    'generic_name': 'Fexofenadine Hydrochloride',
    'image_url': 'images/med_5.png',
    'name': 'Allegra FX (アレグラFX)',
    'price': '¥1,800 - ¥2,400 (28 tablets)',
    'shop_link': 'https://www.amazon.co.jp/s?k=アレグラFX',
    'uses': ['Allergic rhinitis', 'Hay fever (pollen allergy)', 'Sneezing', 'Runny/stuffy nose', 'Itchy eyes'],
    'warnings': [ "Do not use for children under 15 (for under 15, look for 'Allegra FX Junior').",
                  'Do not take with erythromycin or ketoconazole without consulting a doctor.',
                  'Avoid taking with seasonal fruit juices (grapefruit, apple, orange) as they reduce absorption.']},
  { 'benefits': ['Aspirin-free pain relief', 'Gentle on the stomach', 'Safe for individuals with stomach ulcers'],
    'category': 'Pain Reliever',
    'country': 'USA',
    'dosage': 'Adults & Children 12+: Take 2 caplets every 6 hours while symptoms last. Do not exceed 6 caplets (3000 '
              'mg) in 24 hours.',
    'generic_name': 'Acetaminophen (Paracetamol)',
    'image_url': 'images/med_6.png',
    'name': 'Tylenol Extra Strength',
    'price': '$9.00 - $13.00 (100 caplets)',
    'shop_link': 'https://www.amazon.com/s?k=Tylenol+Extra+Strength',
    'uses': ['Headaches', 'Muscle aches', 'Backache', 'Minor arthritis pain', 'Common cold fever reduction'],
    'warnings': [ 'Severe liver damage may occur if you take more than the maximum daily amount or consume 3+ '
                  'alcoholic drinks daily while using.',
                  'Do not use with any other drug containing acetaminophen.',
                  'Stop use if pain worsens or lasts more than 10 days.']},
  { 'benefits': [ 'Effective anti-inflammatory',
                  'Relieves pain at the site of inflammation',
                  'Coated tablets are easy to swallow'],
    'category': 'Pain Reliever',
    'country': 'USA',
    'dosage': 'Adults & Children 12+: Take 1 tablet every 4 to 6 hours while symptoms persist. If pain/fever does not '
              'respond to 1 tablet, 2 tablets may be used. Do not exceed 6 tablets in 24 hours.',
    'generic_name': 'Ibuprofen',
    'image_url': 'images/med_7.png',
    'name': 'Advil / Motrin',
    'price': '$8.00 - $12.00 (100 tablets)',
    'shop_link': 'https://www.amazon.com/s?k=Advil+Ibuprofen',
    'uses': ['Headaches', 'Toothaches', 'Backache', 'Menstrual cramps', 'Fever reduction', 'Minor arthritis pain'],
    'warnings': [ 'May cause severe allergic reactions (hives, facial swelling, asthma).',
                  'NSAID warning: Increases risk of heart attack, stroke, and stomach bleeding.',
                  'Take with food or milk if stomach upset occurs.']},
  { 'benefits': ['Non-drowsy daytime relief', 'Multi-symptom control', 'Available in liquid caps or liquid form'],
    'category': 'Cold & Flu',
    'country': 'USA',
    'dosage': 'Adults & Children 12+: Take 2 LiquiCaps with water every 4 hours. Do not exceed 4 doses (8 LiquiCaps) '
              'in 24 hours.',
    'generic_name': 'Acetaminophen + Dextromethorphan HBr + Phenylephrine HCl',
    'image_url': 'images/med_8.png',
    'name': 'DayQuil Cold & Flu',
    'price': '$12.00 - $16.00 (24 LiquiCaps)',
    'shop_link': 'https://www.amazon.com/s?k=DayQuil',
    'uses': ['Nasal congestion', 'Cough', 'Sore throat', 'Minor aches and pains', 'Fever'],
    'warnings': [ 'Liver damage hazard: Contains Acetaminophen. Do not combine with Tylenol or other cold products.',
                  'Do not use if you are currently taking a monoamine oxidase inhibitor (MAOI).',
                  'Stop use if you get nervous, dizzy, or sleepless.']},
  { 'benefits': [ '5-symptom rapid relief',
                  'Coats stomach lining to soothe irritation',
                  'Antidiarrheal and antimicrobial action'],
    'category': 'Digestive Health',
    'country': 'USA',
    'dosage': 'Adults & Children 12+: 30 mL (1 dose) or 2 chewable tablets every 1/2 to 1 hour as needed. Do not '
              'exceed 8 doses in 24 hours.',
    'generic_name': 'Bismuth Subsalicylate',
    'image_url': 'images/med_9.png',
    'name': 'Pepto-Bismol',
    'price': '$7.00 - $10.00 (12 oz liquid)',
    'shop_link': 'https://www.amazon.com/s?k=Pepto-Bismol',
    'uses': ['Heartburn', 'Indigestion', 'Nausea', 'Upset stomach', 'Diarrhea'],
    'warnings': [ 'Contains salicylate (aspirin relative). Do not give to children/teenagers who have or are '
                  "recovering from chickenpox or flu (Reye's syndrome risk).",
                  'May cause a temporary, harmless darkening of the tongue and/or stool.',
                  'Do not take if you have ulcers or bleeding problems.']},
  { 'benefits': ['24-hour relief', 'Guaranteed non-drowsy antihistamine', 'Indoor and outdoor allergy protection'],
    'category': 'Allergy',
    'country': 'USA',
    'dosage': 'Adults & Children 6+: Take one 10 mg tablet daily. Do not take more than 1 tablet in 24 hours.',
    'generic_name': 'Loratadine',
    'image_url': 'images/med_10.png',
    'name': 'Claritin 24 Hour',
    'price': '$18.00 - $25.00 (30 tablets)',
    'shop_link': 'https://www.amazon.com/s?k=Claritin+Loratadine',
    'uses': ['Runny nose', 'Sneezing', 'Itchy, watery eyes', 'Itching of the nose or throat due to hay fever'],
    'warnings': [ 'Consumers with liver or kidney disease should consult a doctor before use.',
                  'Do not use if you have had an allergic reaction to loratadine.',
                  'Keep out of reach of children.']},
  { 'benefits': ['Highly trusted for fever control', 'Broadly prescribed by doctors in India', 'Cost-effective relief'],
    'category': 'Pain Reliever',
    'country': 'India',
    'dosage': 'Adults: 1 tablet (650 mg) every 4-6 hours as needed. Do not exceed 4 tablets (2600 mg) in 24 hours.',
    'generic_name': 'Paracetamol (Acetaminophen)',
    'image_url': 'images/med_11.png',
    'name': 'Dolo 650',
    'price': 'Rs. 30 - Rs. 40 (15 tablets strip)',
    'shop_link': 'https://www.netmeds.com/catalogsearch/result?q=Dolo+650',
    'uses': ['High fever reduction', 'Headache', 'Body ache', 'Toothache', 'Post-vaccination fever'],
    'warnings': [ 'Do not consume with alcohol (risk of severe liver damage).',
                  'Avoid taking other medications containing paracetamol simultaneously.',
                  'Consult a doctor if fever lasts more than 3 days.']},
  { 'benefits': [ 'Dual active formula targets pain and swelling simultaneously',
                  'Rapid onset of action',
                  'Popular painkiller in India'],
    'category': 'Pain Reliever',
    'country': 'India',
    'dosage': 'Adults: 1 tablet 2 to 3 times a day after meals. Do not take on an empty stomach.',
    'generic_name': 'Ibuprofen + Paracetamol',
    'image_url': 'images/med_12.png',
    'name': 'Combiflam',
    'price': 'Rs. 45 - Rs. 55 (20 tablets strip)',
    'shop_link': 'https://www.netmeds.com/catalogsearch/result?q=Combiflam',
    'uses': ['Muscle pain', 'Joint inflammation', 'Dental pain', 'Fever', 'Rheumatoid arthritis discomfort'],
    'warnings': [ 'Increased risk of stomach ulcers and gastrointestinal bleeding.',
                  'Do not use if allergic to ibuprofen or paracetamol.',
                  'Not recommended for patients with asthma or active stomach ulcers.']},
  { 'benefits': [ 'Quick-acting antacid action',
                  'Simethicone relieves gas bubbles and pressure',
                  'Sugar-free formula available in multiple flavors (Mint, Orange, Mixed Fruit)'],
    'category': 'Digestive Health',
    'country': 'India',
    'dosage': 'Adults: Chew 2 to 4 tablets after meals or take 2-4 teaspoons (10-20ml) of liquid gel.',
    'generic_name': 'Magnesium Hydroxide + Aluminium Hydroxide + Simethicone',
    'image_url': 'images/med_13.png',
    'name': 'Digene Gel / Tablets',
    'price': 'Rs. 120 - Rs. 150 (200ml syrup / 15 tablets)',
    'shop_link': 'https://www.netmeds.com/catalogsearch/result?q=Digene',
    'uses': ['Acidity', 'Heartburn', 'Gas bloating', 'Indigestion', 'Stomach heaviness'],
    'warnings': [ 'Do not take more than the recommended dose.',
                  'Patients with kidney disease should consult a doctor (risk of magnesium buildup).',
                  'Do not use continuously for more than 2 weeks.']},
  { 'benefits': [ 'Starts working in 6 seconds',
                  'Effervescent action neutralizes acid instantly',
                  'Comes in single-use sachets for portability'],
    'category': 'Digestive Health',
    'country': 'India',
    'dosage': 'Adults: Dissolve 1 sachet (5g) or 1 teaspoon of powder in a glass of water (approx. 150ml) and drink '
              'immediately. Repeat after 2-3 hours if needed. Max 2 doses per day.',
    'generic_name': 'Svarjiksara (Sodium Bicarbonate) + Nimbukamra (Citric Acid)',
    'image_url': 'images/med_14.png',
    'name': 'Eno Powder',
    'price': 'Rs. 80 - Rs. 100 (100g bottle / Rs. 9 per sachet)',
    'shop_link': 'https://www.netmeds.com/catalogsearch/result?q=Eno',
    'uses': ['Acid reflux', 'Heartburn', 'Stomach bloating', 'Sour stomach'],
    'warnings': [ 'Contains high sodium; avoid if you have high blood pressure or are on a low-sodium diet.',
                  'Do not take for more than 14 consecutive days.',
                  'Not recommended for children under 12 years.']},
  { 'benefits': ['Effective 24-hour relief', 'Very common OTC antihistamine', 'Reduces allergy swelling and redness'],
    'category': 'Allergy',
    'country': 'India',
    'dosage': 'Adults: 1 tablet (10 mg) once daily, preferably at bedtime as it may cause mild drowsiness.',
    'generic_name': 'Cetirizine Hydrochloride',
    'image_url': 'images/med_15.png',
    'name': 'Cetzip / Cetzine',
    'price': 'Rs. 18 - Rs. 25 (10 tablets strip)',
    'shop_link': 'https://www.netmeds.com/catalogsearch/result?q=Cetzine',
    'uses': [ 'Runny nose',
              'Allergic skin conditions (hives, itching)',
              'Sneezing',
              'Watery eyes',
              'Dust or pet allergy'],
    'warnings': [ 'May cause drowsiness; avoid driving or operating heavy machinery.',
                  'Do not consume alcohol while taking cetirizine.',
                  'Consult doctor if you have kidney or liver impairment.']},
  { 'benefits': [ 'Optizorb technology dissolves up to 5 times faster than standard paracetamol',
                  'Gentle on stomach',
                  'Suitable for elderly patients'],
    'category': 'Pain Reliever',
    'country': 'UK',
    'dosage': 'Adults (12+): Take 1-2 tablets every 4 to 6 hours as needed. Do not exceed 8 tablets (4g) in 24 hours.',
    'generic_name': 'Paracetamol',
    'image_url': 'images/med_16.png',
    'name': 'Panadol Advance',
    'price': '£2.50 - £4.00 (16 tablets)',
    'shop_link': 'https://www.boots.com/sitesearch?searchTerm=Panadol',
    'uses': ['Headaches', 'Migraines', 'Backache', 'Cold & flu fever reduction', 'Toothache', 'Period pain'],
    'warnings': [ 'Never exceed the maximum dose (paracetamol toxicity risk).',
                  'Do not take other paracetamol-containing products simultaneously.',
                  'Consult a doctor if pain lasts more than 3 days or fever persists.']},
  { 'benefits': ['Targeted pain relief', 'Reduces inflammation', 'Available in liquid capsules for faster absorption'],
    'category': 'Pain Reliever',
    'country': 'UK',
    'dosage': 'Adults & Children 12+: Take 1 or 2 tablets with water up to 3 times a day as required. Space doses at '
              'least 4 hours apart. Max 6 tablets in 24 hours.',
    'generic_name': 'Ibuprofen',
    'image_url': 'images/med_17.png',
    'name': 'Nurofen',
    'price': '£2.00 - £3.50 (16 tablets)',
    'shop_link': 'https://www.boots.com/sitesearch?searchTerm=Nurofen',
    'uses': ['Headaches', 'Migraines', 'Backache', 'Muscular pain', 'Dental pain', 'Fever reduction'],
    'warnings': [ 'Do not take if you have a stomach ulcer, perforation, or bleeding.',
                  'May trigger asthma attacks in sensitive individuals.',
                  'Take with a glass of water, ideally with or after food.']},
  { 'benefits': [ 'Forms a protective raft over stomach contents to block acid',
                  'Neutralizes excess acid',
                  'Safe for use during pregnancy and breastfeeding'],
    'category': 'Digestive Health',
    'country': 'UK',
    'dosage': 'Adults & Children 12+: Take 10-20ml (two to four 5ml spoonfuls) of liquid or chew 2-4 tablets after '
              'meals and at bedtime.',
    'generic_name': 'Sodium Alginate + Sodium Bicarbonate + Calcium Carbonate',
    'image_url': 'images/med_18.png',
    'name': 'Gaviscon Double Action',
    'price': '£6.00 - £8.50 (300ml liquid)',
    'shop_link': 'https://www.boots.com/sitesearch?searchTerm=Gaviscon',
    'uses': ['Heartburn', 'Acid indigestion', 'Reflux symptoms after meals or during pregnancy'],
    'warnings': [ 'Contains sodium and calcium. Consult doctor if on restricted sodium/calcium diets.',
                  'Do not take within 2 hours of taking other medicines (as it can affect absorption).',
                  'If symptoms persist after 7 days, consult your doctor.']},
  { 'benefits': [ 'Once-a-day allergy relief',
                  'Relieves both nasal and ocular allergy symptoms',
                  'Max strength non-drowsy formulation (relative to older antihistamines)'],
    'category': 'Allergy',
    'country': 'UK',
    'dosage': 'Adults & Children 6+: Take 1 tablet daily with a glass of water.',
    'generic_name': 'Cetirizine Hydrochloride',
    'image_url': 'images/med_19.png',
    'name': 'Piriteze / Piri Allergy',
    'price': '£4.50 - £7.00 (30 tablets)',
    'shop_link': 'https://www.boots.com/sitesearch?searchTerm=Piriteze',
    'uses': [ 'Hay fever',
              'Skin allergies (hives, itchiness)',
              'Pet allergies',
              'Dust mite allergy',
              'Mould spore allergy'],
    'warnings': [ 'May cause drowsiness in some users; avoid driving if affected.',
                  'Consult a pharmacist if you have kidney problems.',
                  'Avoid excessive alcohol intake while using.']},
  { 'benefits': [ 'Highly standard French fever and pain reducer',
                  'Extremely gentle on the stomach',
                  'Fast-acting formulation'],
    'category': 'Pain Reliever',
    'country': 'France',
    'dosage': 'Adults: Take 1 to 2 tablets of 500mg (or 1 tablet of 1000mg) every 4 to 6 hours. Do not exceed 4g '
              '(4000mg) in 24 hours.',
    'generic_name': 'Paracetamol',
    'image_url': 'images/med_20.png',
    'name': 'Doliprane',
    'price': '€2.00 - €3.50 (16 tablets)',
    'shop_link': 'https://www.pharma-gdd.com/fr/doliprane-500-mg-gellules',
    'uses': ['Headaches', 'Fever reduction', 'Toothaches', 'Period pain', 'Flu-like symptoms'],
    'warnings': [ 'Do not exceed the recommended dose to avoid severe liver damage.',
                  'Do not consume alcohol while taking paracetamol.',
                  'Do not take with other paracetamol-containing medications.']},
  { 'benefits': [ 'Targets smooth muscle spasms directly',
                  'Acts quickly to relieve cramping and digestive pain',
                  'Very famous standard French home remedy'],
    'category': 'Digestive Health',
    'country': 'France',
    'dosage': 'Adults: Take 2 tablets at the time of the spasm. Repeat if necessary, up to 6 tablets per day.',
    'generic_name': 'Phloroglucinol',
    'image_url': 'images/med_21.png',
    'name': 'Spasfon',
    'price': '€3.00 - €4.50 (30 tablets)',
    'shop_link': 'https://www.pharma-gdd.com/fr/spasfon-comprimes',
    'uses': ['Stomach cramps', 'Abdominal pain', 'Bowel spasms', 'Renal colic pain'],
    'warnings': [ 'Contains lactose and sucrose; consult doctor if intolerant.',
                  'Consult physician if symptoms do not improve within 3 days.',
                  'Do not take if you have severe allergic reactions to phloroglucinol.']},
  { 'benefits': [ 'Most popular standard pain reliever in Spain',
                  'Rapid action on fever and symptoms',
                  'Aspirin-free relief'],
    'category': 'Pain Reliever',
    'country': 'Spain',
    'dosage': 'Adults: 1 tablet (650mg or 1g) every 4 to 6 hours as needed. Max 3g per day.',
    'generic_name': 'Paracetamol',
    'image_url': 'images/med_22.png',
    'name': 'Gelocatil',
    'price': '€2.50 - €4.00 (20 tablets)',
    'shop_link': 'https://www.promofarma.com/es/gelocatil-1g-10-comprimes',
    'uses': ['Headaches', 'Fever reduction', 'Mild to moderate pain', 'Muscle ache'],
    'warnings': [ 'Liver warning: Do not exceed maximum daily dosage.',
                  'Avoid taking other medications containing acetaminophen/paracetamol.',
                  'Consult a doctor if symptoms persist past 3-5 days.']},
  { 'benefits': [ 'Rapidly neutralizes stomach acid within seconds',
                  'Relieves burning sensation in the esophagus',
                  'Highly trusted antacid brand in Spain'],
    'category': 'Digestive Health',
    'country': 'Spain',
    'dosage': 'Adults: Take 1 sachet or 1-2 chewable tablets (500mg) 30 to 60 minutes after meals or when symptoms '
              'appear. Max 8g per day.',
    'generic_name': 'Almagate',
    'image_url': 'images/med_23.png',
    'name': 'Almax',
    'price': '€6.00 - €8.50 (30 chewable tablets)',
    'shop_link': 'https://www.promofarma.com/es/almax-500mg-18-sobres',
    'uses': ['Heartburn', 'Acid reflux', 'Indigestion', 'Sour stomach'],
    'warnings': [ 'Contains aluminum and magnesium; consult doctor if kidney disease is present.',
                  'Do not use continuously for more than 2 weeks.',
                  'Can interfere with absorption of other medications; space doses by 2 hours.']},
  { 'benefits': [ "Germany's most popular multi-symptom cold capsule",
                  'Vitamin C supports the immune system',
                  'Caffeine enhances the speed of pain relief'],
    'category': 'Cold & Flu',
    'country': 'Germany',
    'dosage': 'Adults: Take 2 capsules in the morning, midday, and evening with a glass of water.',
    'generic_name': 'Paracetamol + Ascorbic Acid (Vitamin C) + Caffeine + Chlorpheniramine Maleate',
    'image_url': 'images/med_24.png',
    'name': 'Grippostad C',
    'price': '€9.00 - €12.50 (24 capsules)',
    'shop_link': 'https://www.shop-apotheke.com/arzneimittel/104192/grippostad-c.htm',
    'uses': ['Headache', 'Limb pain', 'Runny nose', 'Dry cough', 'Fever reduction'],
    'warnings': [ 'Causes drowsiness. Do not drive or operate machinery.',
                  'Contains paracetamol; do not combine with other paracetamol products.',
                  'Consult doctor if you have high blood pressure or heart problems.']},
  { 'benefits': [ 'German-developed targeted spasmolytic',
                  'Relaxes abdominal muscles directly rather than masking pain',
                  'Fast, localized relief'],
    'category': 'Digestive Health',
    'country': 'Germany',
    'dosage': 'Adults: Take 1 to 2 tablets, 3 times a day, with plenty of water. Space doses at least 4 hours apart.',
    'generic_name': 'Hyoscine Butylbromide',
    'image_url': 'images/med_25.png',
    'name': 'Buscopan',
    'price': '€5.50 - €8.00 (20 tablets)',
    'shop_link': 'https://www.shop-apotheke.com/arzneimittel/3184654/buscopan-dragees.htm',
    'uses': ['Abdominal cramps', 'Stomach spasms', 'Irritable bowel syndrome (IBS) pain', 'Menstrual pain'],
    'warnings': [ 'Do not take if you have glaucoma, severe urinary retention, or myasthenia gravis.',
                  'Consult doctor if cramps are accompanied by fever, vomiting, or blood in stool.',
                  'May cause dry mouth or blurred vision.']},
  { 'benefits': ['Highly popular, fast-acting Korean headache relief', "Known as 'Korea's national pain reliever'"],
    'category': 'Pain Reliever',
    'country': 'South Korea',
    'dosage': 'Adults: Take 1 tablet up to 3 times a day, preferably after meals. Space doses at least 4 hours apart.',
    'generic_name': 'Acetaminophen + Isopropylantipyrine + Caffeine Anhydrous',
    'image_url': 'images/med_26.png',
    'name': 'Geworin',
    'price': '₩3,500 - ₩5,000 (10 tablets)',
    'shop_link': 'https://search.shopping.naver.com/search/all?query=게보린',
    'uses': ['Severe headaches', 'Toothaches', 'Menstrual pain', 'Neuralgia', 'Fever reduction'],
    'warnings': [ 'Do not take on an empty stomach.',
                  'Contains Isopropylantipyrine; do not take if allergic or sensitive to pyrazolone compounds.',
                  'Limit use to short durations; consult doctor if symptoms last more than 3 days.']},
  { 'benefits': [ 'Advanced Korean digestive enzyme formulation',
                  'Combines multiple natural enzymes to break down fats, carbs, and proteins',
                  'Simethicone relieves flatulence'],
    'category': 'Digestive Health',
    'country': 'South Korea',
    'dosage': 'Adults: Take 1 tablet after meals with warm water, up to 3 times a day.',
    'generic_name': 'Pancreatin + Hemicellulase + Bile Extract + Simethicone + Diastase',
    'image_url': 'images/med_27.png',
    'name': 'Festal Gold',
    'price': '₩4,000 - ₩6,000 (10 tablets)',
    'shop_link': 'https://search.shopping.naver.com/search/all?query=페스탈',
    'uses': ['Indigestion', 'Overeating bloating', 'Lack of appetite', 'Gas pressure', 'Heartburn'],
    'warnings': [ 'Do not chew the tablet; swallow whole to ensure enzymes reach the small intestine.',
                  'Do not give to infants under 7 years old.',
                  'Consult doctor if you have acute pancreatitis.']},
  { 'benefits': [ 'Highly popular Korean liquid cold medicine',
                  'Fast absorption due to liquid ampoule formula',
                  'Relieves multiple cold symptoms simultaneously'],
    'category': 'Cold & Flu',
    'country': 'South Korea',
    'dosage': 'Adults (15+): Take 1 bottle (30ml) 3 times a day, preferably 30 minutes after meals.',
    'generic_name': 'Acetaminophen + Chlorpheniramine Maleate + DL-Methylephedrine Hydrochloride + Caffeine Anhydrous',
    'image_url': 'images/med_28.png',
    'name': 'Pancold S (판콜에스)',
    'price': '₩3,000 - ₩4,500 (5 bottles)',
    'shop_link': 'https://search.shopping.naver.com/search/all?query=판콜에스',
    'uses': ['Runny nose', 'Sneezing', 'Sore throat', 'Cough', 'Chills', 'Fever', 'Headache', 'Joint pain'],
    'warnings': [ 'Do not give to children under 15 years old without medical advice.',
                  'Contains acetaminophen; avoid taking other medications containing acetaminophen to prevent liver '
                  'damage.',
                  'May cause drowsiness; avoid driving or operating machinery.',
                  'Do not drink alcohol while taking this medicine.']},
  { 'benefits': [ 'Famous Korean gel-type antacid pouch',
                  'Coats the stomach lining for immediate acid relief',
                  'Simethicone helps disperse trapped gas bubbles'],
    'category': 'Digestive Health',
    'country': 'South Korea',
    'dosage': 'Adults: Take 1 packet (15ml) between meals or at bedtime, up to 4 times a day. Shake well before '
              'taking.',
    'generic_name': 'Aluminium Hydroxide + Magnesium Hydroxide + Simethicone',
    'image_url': 'images/med_29.png',
    'name': 'Gelfos M (겔포스엠)',
    'price': '₩4,500 - ₩6,000 (4 packets)',
    'shop_link': 'https://search.shopping.naver.com/search/all?query=겔포스엠',
    'uses': ['Heartburn', 'Stomach acid reflux', 'Gastric discomfort', 'Bloating', 'Gas pain'],
    'warnings': [ 'Do not take more than 4 packets in 24 hours.',
                  'Consult a doctor if you have kidney disease.',
                  'Do not use continuously for more than 2 weeks without consulting a doctor.']},
  { 'benefits': [ 'Rapid 24-hour relief from seasonal and perennial allergies',
                  'Treats both nasal and skin allergy symptoms',
                  'Standard trusted global brand antihistamine'],
    'category': 'Allergy',
    'country': 'South Korea',
    'dosage': 'Adults and children over 12: Take 1 tablet (10mg) once daily with water.',
    'generic_name': 'Cetirizine Hydrochloride',
    'image_url': 'images/med_30.png',
    'name': 'Zyrtec (지르텍)',
    'price': '₩4,500 - ₩5,500 (10 tablets)',
    'shop_link': 'https://search.shopping.naver.com/search/all?query=지르텍',
    'uses': ['Allergic rhinitis', 'Hay fever', 'Sneezing', 'Runny nose', 'Itchy eyes', 'Urticaria/Hives'],
    'warnings': [ 'May cause mild drowsiness in some individuals. Use caution when driving.',
                  'Avoid alcohol consumption while taking this medication.',
                  'Consult doctor if you have severe renal impairment.']},
  { 'benefits': [ 'Dual action day & night formula for complete nasal relief',
                  'Decongestant clears blocked sinuses',
                  'Paracetamol reduces pain and fever'],
    'category': 'Cold & Flu',
    'country': 'France',
    'dosage': 'Day (Light tablets): Take 1 tablet up to 3 times a day (morning, midday, afternoon). Night (Dark '
              'tablets): Take 1 tablet before bedtime. Space doses at least 4 hours apart.',
    'generic_name': 'Pseudoephedrine Hydrochloride + Paracetamol',
    'image_url': 'images/med_31.png',
    'name': 'Humex Rhume',
    'price': '€6.00 - €8.50 (16 tablets)',
    'shop_link': 'https://www.google.fr/search?q=Humex+Rhume',
    'uses': ['Stuffy nose/Nasal congestion', 'Headache', 'Fever reduction', 'Runny nose'],
    'warnings': [ 'Do not use if under 15 years old.',
                  'Do not take with other nasal decongestants.',
                  'Contraindicated for severe high blood pressure or heart disease.',
                  'Strictly limit to 4 days of treatment.']},
  { 'benefits': [ 'Forms a protective physical raft on top of stomach contents',
                  'Prevents acid from rising back up into the esophagus',
                  'Fast acting relief, typically within 5 minutes'],
    'category': 'Digestive Health',
    'country': 'France',
    'dosage': 'Adults (12+): Take 1 packet (suspension) or 1-2 chewable tablets after meals and before bedtime. Do not '
              'exceed 4 doses per day.',
    'generic_name': 'Sodium Alginate + Potassium Bicarbonate',
    'image_url': 'images/med_32.png',
    'name': 'Gaviscon Pro',
    'price': '€5.50 - €7.50 (12 sachets)',
    'shop_link': 'https://www.google.fr/search?q=Gaviscon+Pro',
    'uses': ['Acid reflux', 'Heartburn', 'Stomach burn', 'Regurgitation'],
    'warnings': [ 'Contains sodium and calcium; consult doctor if on a low-sodium diet.',
                  'If symptoms persist after 7 days, consult a physician.',
                  'Space at least 2 hours apart from other oral medications.']},
  { 'benefits': [ 'Non-drowsy 24-hour antihistamine',
                  'Effective for both hay fever and skin allergies',
                  'Very popular French household allergy relief'],
    'category': 'Allergy',
    'country': 'France',
    'dosage': 'Adults (12+): Take 1 tablet (10mg) daily with a glass of water.',
    'generic_name': 'Cetirizine Dihydrochloride',
    'image_url': 'images/med_33.png',
    'name': 'Cetirizine Biogaran',
    'price': '€3.50 - €5.00 (7 tablets)',
    'shop_link': 'https://www.google.fr/search?q=Cetirizine+Biogaran',
    'uses': ['Nasal allergy symptoms', 'Ocular allergy symptoms (itchy, watery eyes)', 'Chronic hives/urticaria'],
    'warnings': [ 'Use with caution when driving as it can cause mild drowsiness in some users.',
                  'Avoid alcohol while taking this medicine.',
                  'Consult a doctor if you have kidney problems.']},
  { 'benefits': [ "Spain's most popular all-in-one multi-symptom cold relief",
                  'Suppresses dry, hacking coughs',
                  'Chlorpheniramine dries up runny noses'],
    'category': 'Cold & Flu',
    'country': 'Spain',
    'dosage': 'Adults and adolescents (14+): Dissolve 1 sachet in a glass of water, 3 to 4 times daily. Space doses at '
              'least 6 hours apart.',
    'generic_name': 'Paracetamol + Chlorpheniramine Maleate + Dextromethorphan Hydrobromide + Caffeine + Vitamin C',
    'image_url': 'images/med_34.png',
    'name': 'Frenadol Complex',
    'price': '€7.50 - €9.50 (10 sachets)',
    'shop_link': 'https://www.google.es/search?q=Frenadol+Complex',
    'uses': ['Dry cough', 'Runny nose', 'Fever reduction', 'Sneezing', 'General body aches'],
    'warnings': [ 'Do not take if you have liver disease or respiratory failure.',
                  'May cause drowsiness; do not drive or operate machinery.',
                  'Avoid alcohol during treatment.',
                  'Do not take with other paracetamol products.']},
  { 'benefits': [ 'Clinically proven herbal formulation',
                  'Targeted multi-symptom relief for functional dyspepsia',
                  'Relaxes stomach muscles and reduces flatulence'],
    'category': 'Digestive Health',
    'country': 'Spain',
    'dosage': 'Adults (12+): Take 20 drops in some warm water 3 times daily, before or during meals.',
    'generic_name': 'Liquid herbal extracts (Bitter Candytuft, Chamomile, Peppermint, Licorice, Milk Thistle)',
    'image_url': 'images/med_35.png',
    'name': 'Iberogast',
    'price': '€12.00 - €15.00 (20ml drops)',
    'shop_link': 'https://www.google.es/search?q=Iberogast',
    'uses': ['Irritable stomach', 'Bloating', 'Indigestion', 'Stomach cramps', 'Nausea', 'Heartburn'],
    'warnings': [ 'Do not use if you have a history of liver disease.',
                  'Consult doctor if symptoms do not improve after 7 days.',
                  'Not recommended for pregnant or breastfeeding women.']},
  { 'benefits': [ 'Second-generation non-drowsy antihistamine',
                  'Provides rapid and long-lasting 24-hour symptom relief',
                  'High safety profile'],
    'category': 'Allergy',
    'country': 'Spain',
    'dosage': 'Adults: Take 1 tablet (10mg or 20mg depending on severity) once daily with water.',
    'generic_name': 'Ebastine',
    'image_url': 'images/med_36.png',
    'name': 'Ebastina Normon',
    'price': '€4.50 - €6.50 (20 tablets)',
    'shop_link': 'https://www.google.es/search?q=Ebastina+Normon',
    'uses': [ 'Allergic rhinitis (hay fever)',
              'Allergic conjunctivitis',
              'Chronic urticaria (hives)',
              'Itchy skin rashes'],
    'warnings': [ 'Consult a doctor if you have severe liver impairment.',
                  'Generally non-drowsy, but monitor personal response before driving.',
                  'Not recommended during pregnancy.']},
  { 'benefits': [ 'Micro-fine aspirin particles dissolve and absorb twice as fast',
                  'Fast-acting direct pain relief',
                  'Convenient chewable/fast melt granules without water'],
    'category': 'Pain Reliever',
    'country': 'Germany',
    'dosage': 'Adults (15+): Take 1-2 packets of granules directly on the tongue. Max 6 packets per day. Space doses '
              'by at least 4-6 hours.',
    'generic_name': 'Aspirin (Acetylsalicylic Acid)',
    'image_url': 'images/med_37.png',
    'name': 'Aspirin Effect',
    'price': '€5.00 - €7.50 (10 packets)',
    'shop_link': 'https://www.google.de/search?q=Aspirin+Effect',
    'uses': ['Headaches', 'Fever', 'Toothache', 'Muscle pain', 'Mild joint pain'],
    'warnings': [ "Do not give to children under 15 years old (risk of Reye's syndrome).",
                  'Do not use if you have stomach ulcers or bleeding disorders.',
                  'Do not take during the last 3 months of pregnancy.',
                  'Consult doctor if taking blood thinners.']},
  { 'benefits': [ 'Highly popular natural German gastrointestinal relief',
                  'Relaxes and strengthens stomach muscles based on what is needed',
                  'Fast relief from functional dyspepsia'],
    'category': 'Digestive Health',
    'country': 'Germany',
    'dosage': 'Adults: Take 20 drops 3 times a day in warm water before or with meals.',
    'generic_name': 'Herbal extract blend (Bitter Candytuft, Lemon Balm, Peppermint, Chamomile)',
    'image_url': 'images/med_38.png',
    'name': 'Iberogast Classic',
    'price': '€11.50 - €14.50 (20ml)',
    'shop_link': 'https://www.google.de/search?q=Iberogast+Classic',
    'uses': ['Irritable stomach', 'Stomach ache', 'Bloating', 'Nausea', 'Heartburn'],
    'warnings': [ 'Contains 31% alcohol by volume.',
                  'Do not use if you have active liver disease.',
                  'Consult a doctor if symptoms persist after 1 week.']},
  { 'benefits': [ 'Standard German non-drowsy 24-hour antihistamine',
                  'High efficacy for seasonal and chronic allergies',
                  'Cost-effective, highly trusted brand'],
    'category': 'Allergy',
    'country': 'Germany',
    'dosage': 'Adults (12+): Take 1 film-coated tablet (10mg) daily, preferably in the evening.',
    'generic_name': 'Cetirizine Dihydrochloride',
    'image_url': 'images/med_39.png',
    'name': 'Cetirizin ratiopharm',
    'price': '€2.50 - €4.50 (7 tablets)',
    'shop_link': 'https://www.google.de/search?q=Cetirizin+ratiopharm',
    'uses': ['Allergic rhinitis', 'Hay fever', 'Sneezing', 'Itchy runny nose', 'Allergic conjunctivitis', 'Hives'],
    'warnings': [ 'May cause mild fatigue; monitor response before driving.',
                  'Avoid alcohol.',
                  'Consult doctor if you have kidney disease.']},
  { 'benefits': [ 'Triple-action fast relief formula',
                  'Propyphenazone acts as a strong NSAID pain reliever',
                  'Caffeine speeds up and enhances painkiller effect'],
    'category': 'Pain Reliever',
    'country': 'India',
    'dosage': 'Adults: Take 1 tablet with water. If needed, take a second dose after 4-6 hours. Do not exceed 3 '
              'tablets in 24 hours.',
    'generic_name': 'Paracetamol + Propyphenazone + Caffeine',
    'image_url': 'images/med_40.png',
    'name': 'Saridon',
    'price': '₹40 - ₹50 (10 tablets)',
    'shop_link': 'https://www.google.co.in/search?q=Saridon',
    'uses': ['Severe headaches', 'Migraines', 'Toothache', 'Fever reduction', 'Period pain'],
    'warnings': [ 'Do not take with other paracetamol/acetaminophen products.',
                  'Contraindicated for children under 12 years old.',
                  'Consult a doctor if you have liver or kidney problems.']},
  { 'benefits': [ "Japan's most famous traditional stomach medicine for 100+ years",
                  'Rapidly normalizes water content in intestines',
                  'Strong herbal antiseptic properties for digestive upset'],
    'category': 'Digestive Health',
    'country': 'Japan',
    'dosage': 'Adults (15+): 3 pills, 3 times daily. Children (11-14): 2 pills; (8-10): 1.5 pills; (5-7): 1 pill, 3 times daily. Under 5: Do not use.',
              'in the tooth cavity.',
    'generic_name': 'Wood Creosote + Powdered Gambir + Powdered Phellodendron Bark',
    'image_url': 'images/med_41.png',
    'name': 'Seirogan (正露丸)',
    'price': '¥800 - ¥1,200 (100 pills)',
    'shop_link': 'https://www.amazon.co.jp/s?k=正露丸',
    'uses': [ 'Diarrhea',
              'Food poisoning diarrhea',
              'Soft stools',
              'Indigestion stomach ache',
              'Toothache (applied to cavity)'],
    'warnings': [ 'Has a very strong, distinct medicinal odor.',
                  'Do not give to children under 5 years old.',
                  'Consult doctor if you have high fever or bloody stools.']},
  { 'benefits': [ 'Traditional herbal throat remedy',
                  'Melts instantly in mouth without water',
                  'Soothes throat membranes immediately'],
    'category': 'Cold & Flu',
    'country': 'Japan',
    'dosage': 'Adults (15+): 1 stick, up to 6 times daily. Children (11-14): 2/3 stick; (7-10): 1/2 stick; (3-6): 1/3 stick, up to 6 times daily without water.',
              'apart.',
    'generic_name': 'Platycodon Fluid Extract + Senega + Apricot Kernel',
    'image_url': 'images/med_42.png',
    'name': 'Ryukakusan Direct (龍角散ダイレクト)',
    'price': '¥600 - ¥800 (16 sticks)',
    'shop_link': 'https://www.amazon.co.jp/s?k=龍角散ダイレクト',
    'uses': ['Sore throat', 'Throat irritation', 'Coughing', 'Hoarseness'],
    'warnings': [ 'Do not give to children under 3 years old.',
                  'Consult a doctor if you have high fever or chronic cough.']},
  { 'benefits': [ 'Contains 3 strains of live lactic acid bacteria',
                  'Reaches intestines alive to restore gut flora balance',
                  'Gentle formula suitable for all ages'],
    'category': 'Digestive Health',
    'country': 'Japan',
    'dosage': 'Adults (15+): 3 tablets, 3 times daily. Children (5-14): 2 tablets, 3 times daily. Under 5: Do not use.',
    'generic_name': 'Bifidobacterium + Streptococcus faecalis + Lactobacillus acidophilus',
    'image_url': 'images/med_43.png',
    'name': 'Shin Biofermin S (新ビオフェルミンS)',
    'price': '¥1,200 - ¥1,600 (350 tablets)',
    'shop_link': 'https://www.amazon.co.jp/s?k=新ビオフェルミンS',
    'uses': ['Regulation of intestines', 'Bloating', 'Constipation', 'Soft stools'],
    'warnings': ['Do not give to infants under 5 years old.', 'Consult doctor if receiving other medical treatment.']},
  { 'benefits': [ 'Extremely refreshing sensation',
                  'Relieves eye strain and irritation rapidly',
                  'Protects corneal surface'],
    'category': 'Allergy',
    'country': 'Japan',
    'dosage': 'Instill 2 to 3 drops at a time, 5 to 6 times a day.',
    'generic_name': 'Neostigmine Methylsulfate + Taurine + L-Aspartate',
    'image_url': 'images/med_44.png',
    'name': 'Sante FX Neo (サンテFXネオ)',
    'price': '¥500 - ¥700 (12ml)',
    'shop_link': 'https://www.amazon.co.jp/s?k=サンテFXネオ',
    'uses': ['Eye fatigue', 'Itchy eyes', 'Red eyes', 'Blurry vision'],
    'warnings': [ 'Do not use while wearing soft contact lenses.',
                  'Excessive use may cause glare or red eyes.',
                  'Avoid touching dropper tip to eyelids or lashes.']},
  { 'benefits': [ 'Highly popular pain relief patch',
                  'Flexible patch conforms to joints',
                  'Soothing heat and cold action'],
    'category': 'Pain Reliever',
    'country': 'Japan',
    'dosage': 'Clean and dry the affected area. Apply 1 patch up to 3 to 4 times daily.',
    'generic_name': 'Methyl Salicylate + L-Menthol + Tocopherol Acetate',
    'image_url': 'images/med_45.png',
    'name': 'Salonpas (サロンパス)',
    'price': '¥800 - ¥1,200 (140 patches)',
    'shop_link': 'https://www.amazon.co.jp/s?k=サロンパス',
    'uses': ['Stiff shoulder', 'Muscle pain', 'Joint pain', 'Backache', 'Bruises'],
    'warnings': [ 'Do not apply to open wounds or irritated skin.',
                  'Remove patch at least 1 hour before bathing.',
                  'Do not use if allergic to aspirin or NSAIDs.']},
  { 'benefits': [ 'Stimulates bowel movements directly',
                  'Strong, reliable constipation relief',
                  'Coated tablet dissolves in intestines'],
    'category': 'Digestive Health',
    'country': 'Japan',
    'dosage': 'Adults (15+): 2 tablets once daily before bed. Children (11-14): 1-2 tablets once daily. Under 11: Do not use.',
    'generic_name': 'Bisacodyl',
    'image_url': 'images/med_46.png',
    'name': 'Colac (コーラック)',
    'price': '¥900 - ¥1,300 (120 tablets)',
    'shop_link': 'https://www.amazon.co.jp/s?k=コーラック',
    'uses': ['Constipation', 'Abdominal bloating due to constipation'],
    'warnings': [ 'Do not take within 1 hour of drinking milk or antacids.',
                  'Do not crush or chew; swallow whole.',
                  'Do not use continuously for more than 1 week without consulting doctor.']},
  { 'benefits': [ 'Indomethacin penetrates deeply to relieve pain',
                  'Non-greasy gel absorbs quickly',
                  'Cooling menthol sensation'],
    'category': 'Pain Reliever',
    'country': 'Japan',
    'dosage': 'Rub an appropriate amount into the affected area up to 4 times a day.',
    'generic_name': 'Indomethacin',
    'image_url': 'images/med_47.png',
    'name': 'Vantelin Kowa Gel (バンテリンコーワゲル)',
    'price': '¥1,100 - ¥1,500 (35g)',
    'shop_link': 'https://www.amazon.co.jp/s?k=バンテリンコーワゲル',
    'uses': ['Joint pain', 'Muscle pain', 'Elbow pain', 'Sprains'],
    'warnings': [ 'Do not use if under 11 years old.',
                  'Do not use on open wounds, mucus membranes, or eczema.',
                  'Do not wrap the treated area with bandage or plastic wrap.']},
  { 'benefits': [ 'Highly trusted Vitamin B complex formulation',
                  'Aids cell turnover and skin health',
                  'Reduces painful mouth ulcers quickly'],
    'category': 'Allergy',
    'country': 'Japan',
    'dosage': 'Adults (15+): Take 1 tablet twice daily (morning and evening) with water.',
    'generic_name': 'Riboflavin Sodium Phosphate (Vitamin B2) + Pyridoxine Hydrochloride (Vitamin B6)',
    'image_url': 'images/med_48.png',
    'name': 'Chocola BB Plus (チョコラBBプラス)',
    'price': '¥1,800 - ¥2,400 (250 tablets)',
    'shop_link': 'https://www.amazon.co.jp/s?k=チョコラBBプラス',
    'uses': ['Mouth ulcers/canker sores', 'Skin roughness', 'Acne', 'Eye fatigue'],
    'warnings': [ 'May cause urine to turn bright yellow (due to Vitamin B2).',
                  'Consult doctor if skin rash or stomach discomfort occurs.']},
  { 'benefits': [ 'Bi-layer tablet for immediate and 12-hour extended release',
                  'Controls cough and thins mucus concurrently',
                  'No drowsiness'],
    'category': 'Cold & Flu',
    'country': 'USA',
    'dosage': 'Adults (12+): Take 1 or 2 tablets every 12 hours. Do not exceed 4 tablets in 24 hours.',
    'generic_name': 'Guaifenesin + Dextromethorphan HBr',
    'image_url': 'images/med_49.png',
    'name': 'Mucinex DM',
    'price': '$18.00 - $24.00 (20 tablets)',
    'shop_link': 'https://www.google.com/search?q=Mucinex+DM',
    'uses': ['Cough suppression', 'Chest congestion', 'Mucus thinning'],
    'warnings': [ 'Do not use if taking MAO inhibitors.',
                  'Consult doctor if cough lasts more than 7 days or is accompanied by excessive mucus.']},
  { 'benefits': [ 'Works fast to control diarrhea symptoms',
                  'Often resolves diarrhea in a single dose',
                  'Widely recommended by travel clinics'],
    'category': 'Digestive Health',
    'country': 'USA',
    'dosage': 'Adults (12+): Take 2 caplets after the first loose stool; take 1 caplet after each subsequent loose '
              'stool. Max 4 caplets per day.',
    'generic_name': 'Loperamide Hydrochloride',
    'image_url': 'images/med_50.png',
    'name': 'Imodium A-D',
    'price': '$8.00 - $11.00 (12 caplets)',
    'shop_link': 'https://www.google.com/search?q=Imodium+A-D',
    'uses': ['Diarrhea relief', "Traveler's diarrhea control"],
    'warnings': [ 'Do not use if you have bloody or black stools.',
                  'Stay hydrated; drink plenty of fluids while taking.',
                  'Stop use and ask doctor if symptoms last more than 2 days.']},
  { 'benefits': [ 'Highly effective antihistamine for acute allergic reactions',
                  'Helps relieve hives and insect bite itching',
                  'Can also be used as a sleep aid'],
    'category': 'Allergy',
    'country': 'USA',
    'dosage': 'Adults (12+): Take 1 to 2 tablets (25mg to 50mg) every 4 to 6 hours. Do not exceed 6 doses in 24 hours.',
    'generic_name': 'Diphenhydramine Hydrochloride',
    'image_url': 'images/med_51.png',
    'name': 'Benadryl Allergy',
    'price': '$5.00 - $8.00 (24 tablets)',
    'shop_link': 'https://www.google.com/search?q=Benadryl+Allergy',
    'uses': ['Sneezing', 'Runny nose', 'Itchy watery eyes', 'Allergic skin reactions'],
    'warnings': [ 'Causes marked drowsiness. Do not drive or operate machinery.',
                  'Avoid alcohol and other sedatives.',
                  'Do not give to children under 6 years old unless directed by doctor.']},
  { 'benefits': [ 'Fast-acting 24-hour allergy relief',
                  'Works at hour 1 and stays strong all day',
                  'Relieves both indoor and outdoor allergy symptoms'],
    'category': 'Allergy',
    'country': 'USA',
    'dosage': 'Adults (6-64 years): Take 1 tablet (10mg) once daily. Do not take more than one 10mg tablet in 24 '
              'hours.',
    'generic_name': 'Cetirizine Hydrochloride',
    'image_url': 'images/med_52.png',
    'name': 'Zyrtec Allergy',
    'price': '$15.00 - $20.00 (30 tablets)',
    'shop_link': 'https://www.google.com/search?q=Zyrtec+Allergy',
    'uses': ['Runny nose', 'Sneezing', 'Itchy watery eyes', 'Itchy nose or throat'],
    'warnings': [ 'May cause drowsiness in some individuals; monitor reaction.',
                  'Consult doctor if you have liver or kidney disease.']},
  { 'benefits': [ 'Triple action formula proven highly effective against migraines',
                  'Caffeine enhances the speed and potency of pain relievers',
                  'Clinically proven to start working in 30 minutes'],
    'category': 'Pain Reliever',
    'country': 'USA',
    'dosage': 'Adults (18+): Take 2 caplets with a glass of water. Do not exceed 2 caplets in 24 hours unless directed '
              'by doctor.',
    'generic_name': 'Acetaminophen + Aspirin + Caffeine',
    'image_url': 'images/med_53.png',
    'name': 'Excedrin Migraine',
    'price': '$12.00 - $16.00 (100 caplets)',
    'shop_link': 'https://www.google.com/search?q=Excedrin+Migraine',
    'uses': ['Migraine headache', 'Sensitivity to light/sound during headache'],
    'warnings': [ 'Contains aspirin; watch for allergy risk or stomach bleeding.',
                  'Do not take with other products containing acetaminophen.',
                  'Limit caffeine intake from other sources while taking.']},
  { 'benefits': [ 'Multi-symptom cold relief tablet',
                  'Clears nasal congestion quickly',
                  'Very common and widely trusted Indian over-the-counter medicine'],
    'category': 'Cold & Flu',
    'country': 'India',
    'dosage': 'Adults: Take 1 tablet every 4 to 6 hours as needed. Do not exceed 4 tablets in 24 hours.',
    'generic_name': 'Paracetamol + Phenylephrine Hydrochloride + Caffeine',
    'image_url': 'images/med_54.png',
    'name': 'Vicks Action 500',
    'price': '₹15 - ₹25 (10 tablets)',
    'shop_link': 'https://www.google.co.in/search?q=Vicks+Action+500',
    'uses': ['Blocked nose', 'Headache', 'Body ache', 'Sore throat', 'Fever'],
    'warnings': [ 'Do not take with other paracetamol-containing products.',
                  'May cause mild drowsiness or elevated heart rate.',
                  'Not recommended for children under 12 years.']},
  { 'benefits': [ 'Formulated for faster headache relief',
                  'Caffeine improves paracetamol absorption',
                  'Gentle on stomach'],
    'category': 'Pain Reliever',
    'country': 'India',
    'dosage': 'Adults: Take 1 to 2 tablets every 4 to 6 hours. Do not exceed 8 tablets in 24 hours.',
    'generic_name': 'Paracetamol + Caffeine',
    'image_url': 'images/med_55.png',
    'name': 'Crocin Pain Relief',
    'price': '₹30 - ₹40 (15 tablets)',
    'shop_link': 'https://www.google.co.in/search?q=Crocin+Pain+Relief',
    'uses': ['Headaches', 'Tension headaches', 'Toothache', 'Muscle ache'],
    'warnings': [ 'Avoid taking other paracetamol products concurrently.',
                  'Limit caffeine-containing drinks while taking this medicine.',
                  'Consult doctor if pain persists more than 3 days.']},
  { 'benefits': [ 'Dual action: antacid + antiflatulent',
                  'Provides quick relief from acid reflux',
                  'Dimethicone reduces gas bubbles to ease bloating'],
    'category': 'Digestive Health',
    'country': 'India',
    'dosage': 'Adults: Chew 1 to 2 tablets after meals or when symptoms occur. Do not swallow whole.',
    'generic_name': 'Aluminum Hydroxide + Magnesium Hydroxide + Dimethicone',
    'image_url': 'images/med_56.png',
    'name': 'Gelusil',
    'price': '₹15 - ₹20 (10 tablets)',
    'shop_link': 'https://www.google.co.in/search?q=Gelusil',
    'uses': ['Acidity', 'Heartburn', 'Stomach gas/flatulence', 'Indigestion'],
    'warnings': [ 'Do not exceed 8 tablets a day.',
                  'Consult a doctor if on a low-phosphorus diet.',
                  'May cause constipation or diarrhea in rare cases.']}]

def get_countries():
    """Returns unique list of countries in the database."""
    return sorted(list(set(med["country"] for med in MEDICINE_DATABASE)))

def get_categories(country=None):
    """Returns unique list of categories, optionally filtered by country."""
    if country:
        return sorted(list(set(med["category"] for med in MEDICINE_DATABASE if med["country"] == country)))
    return sorted(list(set(med["category"] for med in MEDICINE_DATABASE)))

def get_medicines_by_filters(country=None, category=None):
    """Filter medicines by country and/or category."""
    results = MEDICINE_DATABASE
    if country:
        results = [med for med in results if med["country"].lower() == country.lower()]
    if category:
        results = [med for med in results if med["category"].lower() == category.lower()]
    return results

def search_local_medicines(query):
    """Search local database for medicine matching query in name, generic_name, uses, or category."""
    if not query:
        return []
    query = query.lower()
    results = []
    for med in MEDICINE_DATABASE:
        if (query in med["name"].lower() or 
            query in med["generic_name"].lower() or 
            query in med["category"].lower() or 
            any(query in use.lower() for use in med["uses"])):
            results.append(med)
    return results
